stage:
  deploy:
    CRON_CONSUMERS_RUNNER:
      _merge: true
      cron_run: true
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\Redis'
    REDIS_USE_SLAVE_CONNECTION: true
    SEARCH_CONFIGURATION:
      _merge: true
      engine: amasty_elastic
  build:
    QUALITY_PATCHES:
      - MDVA-33894
      - MDVA-34023
